// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "GroupPurchaseManagementSystemCORBA.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::_nil() {
  return ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_nil();
}

::CORBA::Boolean GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::is_nil(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr p) {
  return ::CORBA::is_nil(p);

}

void GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::release(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr p) {
  ::CORBA::release(p);
}

void GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::marshalObjRef(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr obj, cdrStream& s) {
  ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_marshalObjRef(obj, s);
}

GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::unmarshalObjRef(cdrStream& s) {
  return ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_unmarshalObjRef(s);
}

void GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_Helper::duplicate(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr
GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_duplicate(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr
GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr
GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr
GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_GroupPurchaseManagementSystemCORBA _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_GroupPurchaseManagementSystemCORBA* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_GroupPurchaseManagementSystemCORBA;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId = "IDL:GroupPurchaseManagementSystemModule/GroupPurchaseManagementSystemCORBA:1.0";


GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA::~_objref_GroupPurchaseManagementSystemCORBA() {
  
}


GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA::_objref_GroupPurchaseManagementSystemCORBA(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA::_ptrToObjRef(const char* id)
{
  if( id == ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId )
    return (::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId) )
    return (::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring
class _0RL_cd_D20D25DB6F0E87D1_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D20D25DB6F0E87D1_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_D20D25DB6F0E87D1_00000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);

}

void _0RL_cd_D20D25DB6F0E87D1_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_D20D25DB6F0E87D1_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_D20D25DB6F0E87D1_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_D20D25DB6F0E87D1_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_D20D25DB6F0E87D1_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_D20D25DB6F0E87D1_00000000* tcd = (_0RL_cd_D20D25DB6F0E87D1_00000000*)cd;
  GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA* impl = (GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA*) svnt->_ptrToInterface(GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId);
  tcd->result = impl->confirmPurchase(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA::confirmPurchase(const char* sellerSecretKey, const char* confirm)
{
  _0RL_cd_D20D25DB6F0E87D1_00000000 _call_desc(_0RL_lcfn_D20D25DB6F0E87D1_10000000, "confirmPurchase", 16);
  _call_desc.arg_0 = sellerSecretKey;
  _call_desc.arg_1 = confirm;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cstring_i_cstring_i_cstring_i_cdouble_i_clong
class _0RL_cd_D20D25DB6F0E87D1_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_D20D25DB6F0E87D1_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::String_var arg_0_;
  const char* arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::String_var arg_2_;
  const char* arg_2;
  ::CORBA::Double arg_3;
  ::CORBA::Long arg_4;
  ::CORBA::Boolean result;
};

void _0RL_cd_D20D25DB6F0E87D1_20000000::marshalArguments(cdrStream& _n)
{
  _n.marshalString(arg_0,0);
  _n.marshalString(arg_1,0);
  _n.marshalString(arg_2,0);
  arg_3 >>= _n;
  arg_4 >>= _n;

}

void _0RL_cd_D20D25DB6F0E87D1_20000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = _n.unmarshalString(0);
  arg_0 = arg_0_.in();
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();
  arg_2_ = _n.unmarshalString(0);
  arg_2 = arg_2_.in();
  (::CORBA::Double&)arg_3 <<= _n;
  (::CORBA::Long&)arg_4 <<= _n;

}

void _0RL_cd_D20D25DB6F0E87D1_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_D20D25DB6F0E87D1_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_D20D25DB6F0E87D1_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_D20D25DB6F0E87D1_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_D20D25DB6F0E87D1_20000000* tcd = (_0RL_cd_D20D25DB6F0E87D1_20000000*)cd;
  GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA* impl = (GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA*) svnt->_ptrToInterface(GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId);
  tcd->result = impl->publishGroupPurchaseItem(tcd->arg_0, tcd->arg_1, tcd->arg_2, tcd->arg_3, tcd->arg_4);


}

::CORBA::Boolean GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA::publishGroupPurchaseItem(const char* sellerSecretKey, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit)
{
  _0RL_cd_D20D25DB6F0E87D1_20000000 _call_desc(_0RL_lcfn_D20D25DB6F0E87D1_30000000, "publishGroupPurchaseItem", 25);
  _call_desc.arg_0 = sellerSecretKey;
  _call_desc.arg_1 = productName;
  _call_desc.arg_2 = introduction;
  _call_desc.arg_3 = price;
  _call_desc.arg_4 = limit;

  _invoke(_call_desc);
  return _call_desc.result;


}
GroupPurchaseManagementSystemModule::_pof_GroupPurchaseManagementSystemCORBA::~_pof_GroupPurchaseManagementSystemCORBA() {}


omniObjRef*
GroupPurchaseManagementSystemModule::_pof_GroupPurchaseManagementSystemCORBA::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::GroupPurchaseManagementSystemModule::_objref_GroupPurchaseManagementSystemCORBA(ior, id);
}


::CORBA::Boolean
GroupPurchaseManagementSystemModule::_pof_GroupPurchaseManagementSystemCORBA::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId) )
    return 1;
  
  return 0;
}

const GroupPurchaseManagementSystemModule::_pof_GroupPurchaseManagementSystemCORBA _the_pof_GroupPurchaseManagementSystemModule_mGroupPurchaseManagementSystemCORBA;

GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA::~_impl_GroupPurchaseManagementSystemCORBA() {}


::CORBA::Boolean
GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "confirmPurchase") ) {

    _0RL_cd_D20D25DB6F0E87D1_00000000 _call_desc(_0RL_lcfn_D20D25DB6F0E87D1_10000000, "confirmPurchase", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "publishGroupPurchaseItem") ) {

    _0RL_cd_D20D25DB6F0E87D1_20000000 _call_desc(_0RL_lcfn_D20D25DB6F0E87D1_30000000, "publishGroupPurchaseItem", 25, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA::_ptrToInterface(const char* id)
{
  if( id == ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId )
    return (::GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId) )
    return (::GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA::_mostDerivedRepoId()
{
  return ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId;
}

POA_GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::~GroupPurchaseManagementSystemCORBA() {}

