// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __GroupPurchaseManagementSystemCORBA_hh__
#define __GroupPurchaseManagementSystemCORBA_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE GroupPurchaseManagementSystemModule

_CORBA_MODULE_BEG

#ifndef __GroupPurchaseManagementSystemModule_mGroupPurchaseManagementSystemCORBA__
#define __GroupPurchaseManagementSystemModule_mGroupPurchaseManagementSystemCORBA__

  class GroupPurchaseManagementSystemCORBA;
  class _objref_GroupPurchaseManagementSystemCORBA;
  class _impl_GroupPurchaseManagementSystemCORBA;
  
  typedef _objref_GroupPurchaseManagementSystemCORBA* GroupPurchaseManagementSystemCORBA_ptr;
  typedef GroupPurchaseManagementSystemCORBA_ptr GroupPurchaseManagementSystemCORBARef;

  class GroupPurchaseManagementSystemCORBA_Helper {
  public:
    typedef GroupPurchaseManagementSystemCORBA_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_GroupPurchaseManagementSystemCORBA, GroupPurchaseManagementSystemCORBA_Helper> GroupPurchaseManagementSystemCORBA_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_GroupPurchaseManagementSystemCORBA,GroupPurchaseManagementSystemCORBA_Helper > GroupPurchaseManagementSystemCORBA_out;

#endif

  // interface GroupPurchaseManagementSystemCORBA
  class GroupPurchaseManagementSystemCORBA {
  public:
    // Declarations for this interface type.
    typedef GroupPurchaseManagementSystemCORBA_ptr _ptr_type;
    typedef GroupPurchaseManagementSystemCORBA_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_GroupPurchaseManagementSystemCORBA :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean confirmPurchase(const char* sellerSecretKey, const char* confirm);
    ::CORBA::Boolean publishGroupPurchaseItem(const char* sellerSecretKey, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit);

    inline _objref_GroupPurchaseManagementSystemCORBA()  { _PR_setobj(0); }  // nil
    _objref_GroupPurchaseManagementSystemCORBA(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_GroupPurchaseManagementSystemCORBA();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_GroupPurchaseManagementSystemCORBA(const _objref_GroupPurchaseManagementSystemCORBA&);
    _objref_GroupPurchaseManagementSystemCORBA& operator = (const _objref_GroupPurchaseManagementSystemCORBA&);
    // not implemented

    friend class GroupPurchaseManagementSystemCORBA;
  };

  class _pof_GroupPurchaseManagementSystemCORBA : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_GroupPurchaseManagementSystemCORBA() : _OMNI_NS(proxyObjectFactory)(GroupPurchaseManagementSystemCORBA::_PD_repoId) {}
    virtual ~_pof_GroupPurchaseManagementSystemCORBA();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_GroupPurchaseManagementSystemCORBA :
    public virtual omniServant
  {
  public:
    virtual ~_impl_GroupPurchaseManagementSystemCORBA();

    virtual ::CORBA::Boolean confirmPurchase(const char* sellerSecretKey, const char* confirm) = 0;
    virtual ::CORBA::Boolean publishGroupPurchaseItem(const char* sellerSecretKey, const char* productName, const char* introduction, ::CORBA::Double price, ::CORBA::Long limit) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_GroupPurchaseManagementSystemModule
_CORBA_MODULE_BEG

  class GroupPurchaseManagementSystemCORBA :
    public virtual GroupPurchaseManagementSystemModule::_impl_GroupPurchaseManagementSystemCORBA,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~GroupPurchaseManagementSystemCORBA();

    inline ::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr _this() {
      return (::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr) _do_this(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_GroupPurchaseManagementSystemModule
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA::_marshalObjRef(::GroupPurchaseManagementSystemModule::GroupPurchaseManagementSystemCORBA_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_GroupPurchaseManagementSystemCORBA
#endif

#endif  // __GroupPurchaseManagementSystemCORBA_hh__

